# Generated by Django 5.2.9 on 2026-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0002_delete_mechanicservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='specialization',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='mechanics', to='booking.service'),
        ),
    ]
